/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.GrandPrixDAO;
import model.User;


import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Entry;
import model.GrandPrix;
import java.time.LocalDate;
import javax.swing.JOptionPane;
    

/**
 *
 * @author Delar
 */



public class SelectGrandPrixFrm extends javax.swing.JFrame {

    /**
     * Creates new form SelectGrandPrixFrm
     */
    
    private User user;
    SelectGrandPrixFrm mainFrm = this;
    
    public SelectGrandPrixFrm(User user) {
        initComponents();
        this.user = user;
        
        GrandPrixDAO grandPriDAO = new GrandPrixDAO();
        ArrayList<GrandPrix> listGrandPrix = grandPriDAO.getListGrandPrix();
        String[][] data = new String[listGrandPrix.size()][5];
        String[] columNames = {"STT", "Chặng đua", "Số vòng đua", "Địa điểm", "Thời gian"};
        
        for(int i = 0; i<listGrandPrix.size(); i++){
            GrandPrix grandPrix = listGrandPrix.get(i);
            data[i][0] = i+1 +"";
            data[i][1] = grandPrix.getName();
            data[i][2] = grandPrix.getNumberOflap() + "";
            data[i][3] = grandPrix.getLocation();
            data[i][4] = String.valueOf(grandPrix.getDate());            
        }
            
        DefaultTableModel dtm = new DefaultTableModel(data, columNames);
//        {
//            
//            @Override
//            public boolean isCellEditable(int row, int column) {
//               return false;
//            }
//        };
                
        tblGrandPrix.setModel(dtm);
        tblGrandPrix.getTableHeader().setReorderingAllowed(false);
        
        ListSelectionModel selectionModel = tblGrandPrix.getSelectionModel();
        
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int selectedRow = tblGrandPrix.getSelectedRow();
                    GrandPrix grandPrix = listGrandPrix.get(selectedRow);

                    if(grandPrix.getDate().compareTo(LocalDate.now()) > 0){
                        Entry entry = new Entry();
                        entry.setGrandPrix(grandPrix);
                        entry.setUser(mainFrm.user);
                        (new SelectRaceTeamFrm(entry)).setVisible(true);
                        mainFrm.dispose();
                    }
                    else {
                        JOptionPane.showMessageDialog(mainFrm, "Chặng đua " + grandPrix.getName().trim() +" đã diễn ra. Chọn chặng đua khác");
                    }
                }
            }
        });
        
        tblGrandPrix.getColumnModel().getColumn(1).setMinWidth(100);
        tblGrandPrix.getColumnModel().getColumn(0).setMaxWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrandPrix = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Select GrandPrix");

        tblGrandPrix.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tblGrandPrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Chặng đua", "Số vòng đua", "Địa điểm", "Thời gian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGrandPrix);
        if (tblGrandPrix.getColumnModel().getColumnCount() > 0) {
            tblGrandPrix.getColumnModel().getColumn(0).setResizable(false);
            tblGrandPrix.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblGrandPrix.getColumnModel().getColumn(1).setResizable(false);
            tblGrandPrix.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGrandPrix;
    // End of variables declaration//GEN-END:variables
}
